include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
    avoid_dynamic_calls: false
    always_put_required_named_parameters_first: false
    avoid_final_parameters: false

analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.config.dart]

