name: task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-134.0.dev <4.0.0'

dependencies:
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
